### ISSUE TITLE
Can't compile TIFF.pas

### ISSUE THREAD

**Issue by code-kot** [mike-lischke/GraphicEx#11]
It requires "zutil.obj". TIFF.pas line 613: 

    {$L zutil.obj}

There is no such file in repository. I found `zutil.c` and `zutil.h` in `3rd party\DelphiZlib\zlib\`. Can I use it to get `zutil.obj`? And if Yes what I need to do to get it?

P.S. I've tried it in Delphi 7 and Delphi 2010

**Comment by mike-lischke** [comment]
For all the C code you need a C compiler. For best compatibility you'd BCB to create object files from the C sources. You can then directly link to them (as it is done in TIFF.pass).
