### ISSUE TITLE
Weird behaviour on dll

### ISSUE THREAD

**Issue by kqha** [mike-lischke/GraphicEx#12]
Since I cannot use/compile GraphicEx in XE7, I made a .dll using Turbo Delphi for GraphicEx images operations, and then call the functions from a host application made in XE7. Up until moments ago, all runs fine, until somehow whenever I close my host app, I got an exception which only occurs when in development (using XE7) but never shows up when run .exe directly.

After nightmare of debugging, I finally locate the problem being in GraphicEx in .dll, by removing it from uses clause, disable/commenting all GraphicEx functions call and then recompile the .dll, and after that the exception in host app never shows again.

**Comment by mike-lischke** [comment]
Might be some incompatibility. [Work is being done as we speak](https://github.com/mike-lischke/GraphicEx/pull/10) to make GraphicEx fit for latest Delphi Compilers

**Comment by mike-lischke** [comment]
@kqha Please pull the latest changes and see if that works for you now.

**Comment by kqha** [comment]
Already pulled the latest changes just a few moments ago, and the same problem is still there :)

**Comment by kqha** [comment]
What I did to confirm the bug:
1. Download the latest GraphicEx
2. Compile it (using Turbo Delphi), found an error on line 9476 in GraphicEx.pas (AlphaFormat:=afDefined;), commented it, and recompile.
3. Open my dll project, uncomment the GraphicEx in uses clause, compile the dll
4. Open my host app project in XE7, run, do nothing, close the app, and the exception still raised.

**Comment by nabbla** [comment]
@kqha  Could you please disable one graphic format after another (in GraphicConfiguration.inc comment {$define ...}) and say what happens then. 

About AlphaFormat: my bad. Wanted to show transparency on bitmap (and it worked) but failed to choose right versions in conditional compilation, because in older versions this property doesn't exist. Will fix soon. 

By the way: maybe the reason to make .dll is gone already. It should compile "as is" and work in XE7.

**Comment by kqha** [comment]
> @kqha Could you please disable one graphic format after another (in GraphicConfiguration.inc comment {$define ...}) and say what happens then.

I'll try this

> By the way: maybe the reason to make .dll is gone already. It should compile "as is" and work in XE7.

For later apps maybe, but for the current one will be quite a hassle since it's being used here and there already :)

**Comment by nabbla** [comment]
@kqha One more question: do you compile exactly .dll or is this .bpl ? With .bpl it is much simpler to use, no problems with memory or passing objects as arguments. I'm pretty sure that GraphicEx can be compiled as binary package which is .bpl, but doubt pretty much about .dll without refactoring all the interfaces altogether (making them C-like with considerations that who allocates memory must free it and so on).

**Comment by mike-lischke** [comment]
No feedback for over 2 months. Closing issue.
