### ISSUE TITLE
Memory leak in PNGGraphic

### ISSUE THREAD

**Issue by brianjford** [mike-lischke/GraphicEx#15]
The old Graphic-Ex used to have a memory leak in TPNGGraphic.LoadFromStream.
I believe this leak still exists (now in TPNGGraphic.LoadFromMemory).

It was described in this thread (in german):  http://www.delphipraxis.net/875740-post2.html

**Comment by brianjford** [comment]
Actually I think I see this was resolved by adding a Free to the end of the TPNGGraphic.ReadImageProperties function..
I think you can close my invalid bug report.  Sorry!

**Comment by mike-lischke** [comment]
Ok :-)
