### ISSUE TITLE
Support for Delphi 10.2 and newer

### ISSUE THREAD

**Issue by uschuster** [mike-lischke/GraphicEx#19]
GraphicEx compiles out of the box for me with Delphi 10.2 and newer. However the graphic formats do not implement TGraphic.CanLoadFromStream and thatswhy Delphi 10.2 and newer are not fully supported.

Background:
As soon as one tries to load TPicture from an empty stream, TPicture thinks that the empty stream is of a GraphicEx graphic class, because the GraphicEx graphic classes are inherited from TBitmap, which has "Result := (Stream.Size - Stream.Position = 0) or ..." in the CanLoadFromStream implementation.

For more information see https://quality.embarcadero.com/browse/RSP-24474
(login for quality portal required!)

When putting GraphicEx in the uses clause instead of registering TNOPGraphic it crashs in any case in TGEDGraphic.ReadImageProperties, because TGEDGraphic.CanLoadFromStream is True and not False.

**Comment by mike-lischke** [comment]
Due to time constraints I depend here on someone else to provide a fix. I'm happy to take PRs here!

**Comment by uschuster** [comment]
The existing CanLoad implementation can be leveraged and the following implementation seams to be sufficient.

```Delphi
class function TGraphicExGraphic.CanLoadFromStream(Stream: TStream): Boolean;
var
  P: Int64;
begin
  P := Stream.Position;
  try
    Result := CanLoad(Stream);
  finally
    Stream.Position := P;
  end;
end;
```

I'll apply the full change including conditional defines in a fork and let you know.
