### ISSUE TITLE
Can't use GraphicEX with XE6

### ISSUE THREAD

**Issue by STEP-Software** [mike-lischke/GraphicEx#9]
I tried to use GraphicEX with DelphiXE6, but got the following errors:
[dcc32 Fehler] JPG.pas(1136): E2065 Ungenügende Forward- oder External-Deklaration: 'jpeg_reset_huff_decode'
[dcc32 Fehler] JPG.pas(1258): E2065 Ungenügende Forward- oder External-Deklaration: '@jfwrite'
[dcc32 Fehler] JPG.pas(1258): E2065 Ungenügende Forward- oder External-Deklaration: '@jfflush'
[dcc32 Fehler] JPG.pas(1258): E2065 Ungenügende Forward- oder External-Deklaration: '@jfread'
best regards 
Patrick

**Comment by mike-lischke** [comment]
Patrick, I just merged a big changeset which is supposed to fix problems like that. Please pul and see if this is the case for you as well.
